Putting it together
BloomGameStudio/BloomDiscordBot pull request #9
Opened 2023-12-11 20:26 UTC by Sarahtonein

2023-12-13 21:02 UTC, Sarahtonein commented
> Can you give a quick overview of what you are doing and trying to achieve and your thoughts

At the moment I am making some changes to how we tag / alert people to events happening in the next 24 hours and I need to include the draft proposal stuff you mentioned the other day.

I am working on setting up discord => snapshot as well. Looking into this further today.

Outside of that, the gov-bot / emotes / update branches have been merged into here and completed / ready to review pending the other changes mentioned above. I can close this PR for now until the other changes have been made.

2023-12-14 12:25 UTC, Balugrizzly requested changes
This is a partial review.
I have stopped because i would highly recommend that you split this up into dedicated PR's with clear structure.

2023-12-14 12:25 UTC, Balugrizzly commented on docker-compose.yml
> +version: '1'
Why are you using version 1 ?

2023-12-14 12:25 UTC, Balugrizzly commented on docker-compose.yml
Can you add a build step here

2023-12-14 12:25 UTC, Balugrizzly commented on emojis/contributors.json
FMT would be nice.

Also combining this into the config might be a consideration. UP to you.

2023-12-14 12:26 UTC, Balugrizzly commented
Btw Pipenv automatically loads env vars.

2023-12-14 21:18 UTC, Sarahtonein commented
> This is a partial review. I have stopped because i would highly recommend that you split this up into dedicated PR's with clear structure.

No worries will do this :)

2023-12-14 21:18 UTC, closed without merging

2023-12-14 21:19 UTC, Sarahtonein commented on docker-compose.yml
> +version: '1'
> Why are you using version 1 ?

Was not sure what version # to use

2023-12-14 21:20 UTC, Sarahtonein commented on docker-compose.yml
> Can you add a build step here

Will do.

2023-12-14 21:20 UTC, Sarahtonein commented on emojis/contributors.json
> FMT would be nice.
> 
> Also combining this into the config might be a consideration. UP to you.

I'll have a look at this :)